import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { getPosts } from '../services/index';
import { FeaturedPosts } from '../sections';

const PostCard = dynamic(() => import('../components/PostCard'), { ssr: false });
const Categories = dynamic(() => import('../components/Categories'), { ssr: false });
const PostWidget = dynamic(() => import('../components/PostWidget'), { ssr: false });
const noSelectStyle = {
  userSelect: 'none',
};

export default function Home({ posts }) {
  return (
    <div className="container mx-auto md:mx-10 md:mx-auto sm:mx-10 sm:mx-auto xs:mx-10 xs:mx-auto mb-8 disable-text-selection" style={noSelectStyle}>
      <Head>
        <title>TJ CMS Web Dev Blog - Connecting The Dots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts />
      <div className="lg:flex gap-8 mx-5">
        <div className="recents">
          <div className="lg:sticky xl:flex lg:block md:hidden sm:hidden xs:hidden relative top-24">
            <PostWidget />
          </div>
        </div>
        <div className="top-24 xl:w-full">
        <h2 className='text-white mb-2 font-semibold text-xl text-shadow'>Latest Posts:</h2>
          {posts.map((post) => (
            <PostCard post={post.node} key={[post.title]} />
          ))}
        </div>
        <div className="categories">
          <div className="lg:sticky xl:flex lg:block md:block sm:hidden xs:hidden relative top-24 w-60 mx-auto">
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {props: { posts }};
}
