import React from 'react';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import { getPosts } from '../services/index';
import { FeaturedPosts } from '../sections';

const PostCard = dynamic(() => import('../components/PostCard'), { ssr: false });
const Categories = dynamic(() => import('../components/Categories'), { ssr: false });
const PostWidget = dynamic(() => import('../components/PostWidget'), { ssr: false });
const noSelectStyle = {
  userSelect: 'none',
};

export default function Home({ posts }) {
  return (
    <div className="container mx-auto px-10 mb-8 disable-text-selection" style={noSelectStyle}>
      <Head>
        <title>TJ CMS Web Dev Blog - Connecting The Dots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts />
      <div className="block lg:flex gap-8">
        <div className="categories">
          <div className="lg:sticky relative top-24">
            <Categories />
          </div>
        </div>
        <div className="top-24">
          {posts.map((post) => (
            <PostCard post={post.node} key={[post.title]} />
          ))}
        </div>
        <div className="recents">
          <div className="lg:sticky relative top-24">
            <PostWidget />
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  return {props: { posts }};
}
